### ISSUE TITLE
[BUG] - Error on listing latest gradle version

### ISSUE THREAD

**Issue by luisangelorjr** [rfrancis/asdf-gradle#12] opened 2022-09-20 14:28 UTC
On run ```asdf install gradle latest``` the version installed is ```4.10.3```.
When I listing using ```asdf list all gradle```:

```
...
7.4.1
7.4.2
7.5.1
2.14.1
2.14.1-rc-1
2.14.1-rc-2
4.10.1
4.10.2
4.10.3
```

Run the below script, I found the root of bug:

https://github.com/rfrancis/asdf-gradle/blob/4adbc6f46837a487d9b04b4e0c681134f74710d5/bin/list-all#L2

**Comment by rfrancis** [comment] 2022-09-20 14:58
I can't reproduce these results with the current version of the plugin.

```
$ asdf latest gradle
7.5.1
```

and

```
$ asdf list all gradle
0.7
0.8
0.9
0.9.1
0.9.2
0.9-rc-1
0.9-rc-2
0.9-rc-3
1.0
[...]
7.4
7.4.1
7.4.2
7.4-rc-1
7.4-rc-2
7.5
7.5.1
7.5-milestone-1
7.5-rc-1
7.5-rc-2
7.5-rc-3
7.5-rc-4
7.5-rc-5
```

Can you (a) make sure you're using the current version of the plugin and (b) give some details about your environment? I'm running under Ubuntu 22.04.

**Comment by luisangelorjr** [comment] 2022-09-21 00:19
Hi!

I'm usign Xubuntu 22.04 (my work partner use Ubuntu 22.04 and with the same error)

![image](https://user-images.githubusercontent.com/22268900/191385895-f66c4f75-d02f-44c3-9c7e-7b2fd41167e4.png)

If I break the entire commannd between sed (4.8) and sort (GNU coreutils 8.32): 

1. the `sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##"`, see the results:
```
7.5.1
7.5
7.5-rc-5
7.5-rc-4
7.5-rc-3
7.5-rc-2
7.5-rc-1
7.5-milestone-1
7.4.2
7.4.1
7.4
7.4-rc-2
7.4-rc-1
7.3.3
7.3.3-rc-1
6.9.2
7.3.2
7.3.1
7.3
7.3-rc-5
7.3-rc-4
7.3-rc-3
7.3-rc-2
7.3-rc-1
6.9.1
7.2
7.2-rc-3
7.2-rc-2
7.2-rc-1
7.1.1
7.1
7.1-rc-2
7.1-rc-1
7.0.2
7.0.1
6.9
6.9-rc-2
6.9-rc-1
7.0
7.0-rc-2
7.0-rc-1
7.0-milestone-3
7.0-milestone-2
6.8.3
6.8.2
7.0-milestone-1
6.8.1
6.8
6.8-rc-5
6.8-rc-4
6.8-rc-3
6.8-rc-2
6.8-rc-1
6.7.1
6.8-milestone-3
6.8-milestone-2
6.7
6.8-milestone-1
6.7-rc-5
6.7-rc-4
6.7-rc-3
6.7-rc-2
6.7-rc-1
6.6.1
6.6
6.6-rc-6
6.6-rc-5
6.6-rc-4
6.6-rc-3
6.6-rc-2
6.6-rc-1
6.6-milestone-3
6.5.1
6.6-milestone-2
6.6-milestone-1
6.5
6.5-rc-1
6.4.1
6.5-milestone-2
6.5-milestone-1
6.4
6.4-rc-4
6.4-rc-3
6.4-rc-2
6.4-rc-1
6.3
6.3-rc-4
6.3-rc-3
6.3-rc-2
6.3-rc-1
6.2.2
6.2.1
6.2
6.2-rc-3
6.2-rc-2
6.2-rc-1
6.1.1
6.1-rc-3
6.1-rc-2
6.1-rc-1
6.1-milestone-3
6.1-milestone-2
6.1-milestone-1
6.1
6.0.1
6.0-rc-3
6.0-rc-2
6.0-rc-1
6.0
5.6.4
5.6.3
5.6.2
5.6.1
5.6-rc-2
5.6-rc-1
5.6
5.5.1
5.5-rc-4
5.5-rc-3
5.5-rc-2
5.5-rc-1
5.5
5.4.1
5.4-rc-1
5.4
5.3.1
5.3-rc-3
5.3-rc-2
5.3-rc-1
5.3
5.2.1
5.2-rc-1
5.2
5.1.1
5.1-rc-3
5.1-rc-2
5.1-rc-1
5.1-milestone-1
5.1
5.0-rc-5
5.0-rc-4
5.0-rc-3
5.0-rc-2
5.0-rc-1
5.0-milestone-1
5.0
4.9-rc-2
4.9-rc-1
4.9
4.8.1
4.8-rc-3
4.8-rc-2
4.8-rc-1
4.8
4.7-rc-2
4.7-rc-1
4.7
4.6-rc-2
4.6-rc-1
4.6
4.5.1
4.5-rc-2
4.5-rc-1
4.5
4.4.1
4.4-rc-6
4.4-rc-5
4.4-rc-4
4.4-rc-3
4.4-rc-2
4.4-rc-1
4.4
4.3.1
4.3-rc-4
4.3-rc-3
4.3-rc-2
4.3-rc-1
4.3
4.2.1
4.2-rc-2
4.2-rc-1
4.2
4.10.3
4.10.2
4.10.1
4.10-rc-3
4.10-rc-2
4.10-rc-1
4.10
4.1-rc-1
4.1-rc-2
4.1-milestone-1
4.1
4.0.2
4.0.1
4.0-rc-3
4.0-rc-2
4.0-rc-1
4.0-milestone-2
4.0-milestone-1
4.0
3.5.1
3.5-rc-3
3.5-rc-2
3.5-rc-1
3.5
3.4.1
3.4-rc-3
3.4-rc-2
3.4-rc-1
3.4
3.3-rc-1
3.3
3.2.1
3.2-rc-3
3.2-rc-2
3.2-rc-1
3.2
3.1-rc-1
3.1
3.0-rc-2
3.0-rc-1
3.0-milestone-2
3.0-milestone-1
3.0
2.9-rc-1
2.9
2.8-rc-2
2.8-rc-1
2.8
2.7-rc-2
2.7-rc-1
2.7
2.6-rc-2
2.6
2.6-rc-1
2.5-rc-2
2.5
2.5-rc-1
2.4-rc-2
2.4-rc-1
2.4
2.3-rc-4
2.3-rc-3
2.3-rc-2
2.3
2.3-rc-1
2.2.1-rc-1
2.2.1
2.2-rc-2
2.2
2.2-rc-1
2.14.1-rc-2
2.14.1
2.14.1-rc-1
2.14-rc-6
2.14-rc-5
2.14-rc-4
2.14-rc-3
2.14-rc-2
2.14-rc-1
2.14
2.13-rc-2
2.13
2.13-rc-1
2.12
2.12-rc-1
2.11-rc-2
2.11-rc-3
2.11-rc-1
2.11
2.10-rc-2
2.10
2.10-rc-1
2.1-rc-4
2.1-rc-3
2.1-rc-2
2.1
2.1-rc-1
2.0-rc-2
2.0
2.0-rc-1
1.9-rc-4
1.9-rc-2
1.9-rc-3
1.9
1.9-rc-1
1.8-rc-2
1.8
1.8-rc-1
1.7-rc-2
1.7
1.7-rc-1
1.6
1.6-rc-1
1.5-rc-2
1.5-rc-3
1.5
1.5-rc-1
1.4-rc-3
1.4-rc-2
1.4-rc-1
1.4
1.3-rc-2
1.3-rc-1
1.3
1.2-rc-1
1.2
1.12-rc-2
1.12
1.12-rc-1
1.11-rc-1
1.11
1.10-rc-2
1.10-rc-1
1.10
1.1-rc-2
1.1
1.1-rc-1
1.0-rc-3
1.0-rc-1
1.0-rc-2
1.0-milestone-9
1.0-milestone-8a
1.0-milestone-7
1.0-milestone-8
1.0-milestone-5
1.0-milestone-6
1.0-milestone-3
1.0-milestone-4
1.0-milestone-2a
1.0-milestone-1
1.0-milestone-2
0.9.2
1.0
0.9-rc-3
0.9.1
0.9-rc-1
0.9-rc-2
0.9
0.7
0.8
```

2. and `sort -t. -n`, see the results:

```
0.7
0.8
0.9
0.9-rc-1
0.9-rc-2
0.9-rc-3
1.0
1.0-milestone-1
1.0-milestone-2
1.0-milestone-2a
1.0-milestone-3
1.0-milestone-4
1.0-milestone-5
1.0-milestone-6
1.0-milestone-7
1.0-milestone-8
1.0-milestone-8a
1.0-milestone-9
1.0-rc-1
1.0-rc-2
1.0-rc-3
1.1
1.1-rc-1
1.1-rc-2
1.2
1.2-rc-1
1.3
1.3-rc-1
1.3-rc-2
1.4
1.4-rc-1
1.4-rc-2
1.4-rc-3
1.5
1.5-rc-1
1.5-rc-2
1.5-rc-3
1.6
1.6-rc-1
1.7
1.7-rc-1
1.7-rc-2
1.8
1.8-rc-1
1.8-rc-2
1.9
1.9-rc-1
1.9-rc-2
1.9-rc-3
1.9-rc-4
2.0
2.0-rc-1
2.0-rc-2
2.1
2.1-rc-1
2.1-rc-2
2.1-rc-3
2.1-rc-4
2.2
2.2-rc-1
2.2-rc-2
2.3
2.3-rc-1
2.3-rc-2
2.3-rc-3
2.3-rc-4
2.4
2.4-rc-1
2.4-rc-2
2.5
2.5-rc-1
2.5-rc-2
2.6
2.6-rc-1
2.6-rc-2
2.7
2.7-rc-1
2.7-rc-2
2.8
2.8-rc-1
2.8-rc-2
2.9
2.9-rc-1
3.0
3.0-milestone-1
3.0-milestone-2
3.0-rc-1
3.0-rc-2
3.1
3.1-rc-1
3.2
3.2-rc-1
3.2-rc-2
3.2-rc-3
3.3
3.3-rc-1
3.4
3.4-rc-1
3.4-rc-2
3.4-rc-3
3.5
3.5-rc-1
3.5-rc-2
3.5-rc-3
4.0
4.0-milestone-1
4.0-milestone-2
4.0-rc-1
4.0-rc-2
4.0-rc-3
4.1
4.1-milestone-1
4.1-rc-1
4.1-rc-2
4.2
4.2-rc-1
4.2-rc-2
4.3
4.3-rc-1
4.3-rc-2
4.3-rc-3
4.3-rc-4
4.4
4.4-rc-1
4.4-rc-2
4.4-rc-3
4.4-rc-4
4.4-rc-5
4.4-rc-6
4.5
4.5-rc-1
4.5-rc-2
4.6
4.6-rc-1
4.6-rc-2
4.7
4.7-rc-1
4.7-rc-2
4.8
4.8-rc-1
4.8-rc-2
4.8-rc-3
4.9
4.9-rc-1
4.9-rc-2
5.0
5.0-milestone-1
5.0-rc-1
5.0-rc-2
5.0-rc-3
5.0-rc-4
5.0-rc-5
5.1
5.1-milestone-1
5.1-rc-1
5.1-rc-2
5.1-rc-3
5.2
5.2-rc-1
5.3
5.3-rc-1
5.3-rc-2
5.3-rc-3
5.4
5.4-rc-1
5.5
5.5-rc-1
5.5-rc-2
5.5-rc-3
5.5-rc-4
5.6
5.6-rc-1
5.6-rc-2
6.0
6.0-rc-1
6.0-rc-2
6.0-rc-3
6.1
6.1-milestone-1
6.1-milestone-2
6.1-milestone-3
6.1-rc-1
6.1-rc-2
6.1-rc-3
6.2
6.2-rc-1
6.2-rc-2
6.2-rc-3
6.3
6.3-rc-1
6.3-rc-2
6.3-rc-3
6.3-rc-4
6.4
6.4-rc-1
6.4-rc-2
6.4-rc-3
6.4-rc-4
6.5
6.5-milestone-1
6.5-milestone-2
6.5-rc-1
6.6
6.6-milestone-1
6.6-milestone-2
6.6-milestone-3
6.6-rc-1
6.6-rc-2
6.6-rc-3
6.6-rc-4
6.6-rc-5
6.6-rc-6
6.7
6.7-rc-1
6.7-rc-2
6.7-rc-3
6.7-rc-4
6.7-rc-5
6.8
6.8-milestone-1
6.8-milestone-2
6.8-milestone-3
6.8-rc-1
6.8-rc-2
6.8-rc-3
6.8-rc-4
6.8-rc-5
6.9
6.9-rc-1
6.9-rc-2
7.0
7.0-milestone-1
7.0-milestone-2
7.0-milestone-3
7.0-rc-1
7.0-rc-2
7.1
7.1-rc-1
7.1-rc-2
7.2
7.2-rc-1
7.2-rc-2
7.2-rc-3
7.3
7.3-rc-1
7.3-rc-2
7.3-rc-3
7.3-rc-4
7.3-rc-5
7.4
7.4-rc-1
7.4-rc-2
7.5
7.5-milestone-1
7.5-rc-1
7.5-rc-2
7.5-rc-3
7.5-rc-4
7.5-rc-5
0.9.1
0.9.2
1.10
1.10-rc-1
1.10-rc-2
1.11
1.11-rc-1
1.12
1.12-rc-1
1.12-rc-2
2.10
2.10-rc-1
2.10-rc-2
2.11
2.11-rc-1
2.11-rc-2
2.11-rc-3
2.12
2.12-rc-1
2.13
2.13-rc-1
2.13-rc-2
2.14
2.14-rc-1
2.14-rc-2
2.14-rc-3
2.14-rc-4
2.14-rc-5
2.14-rc-6
2.2.1
2.2.1-rc-1
3.2.1
3.4.1
3.5.1
4.0.1
4.0.2
4.10
4.10-rc-1
4.10-rc-2
4.10-rc-3
4.2.1
4.3.1
4.4.1
4.5.1
4.8.1
5.1.1
5.2.1
5.3.1
5.4.1
5.5.1
5.6.1
5.6.2
5.6.3
5.6.4
6.0.1
6.1.1
6.2.1
6.2.2
6.4.1
6.5.1
6.6.1
6.7.1
6.8.1
6.8.2
6.8.3
6.9.1
6.9.2
7.0.1
7.0.2
7.1.1
7.3.1
7.3.2
7.3.3
7.3.3-rc-1
7.4.1
7.4.2
7.5.1
2.14.1
2.14.1-rc-1
2.14.1-rc-2
4.10.1
4.10.2
4.10.3
```

**Comment by luisangelorjr** [comment] 2022-09-21 00:21
I think the problem is with the -n argument on sort command:

Without -n:
`curl -s https://services.gradle.org/distributions/ | grep -e "distributions.*-bin.zip\"" | sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##" | sort -t.`

```
0.7
0.8
0.9
0.9.1
0.9.2
0.9-rc-1
0.9-rc-2
0.9-rc-3
1.0
1.0-milestone-1
1.0-milestone-2
1.0-milestone-2a
1.0-milestone-3
1.0-milestone-4
1.0-milestone-5
1.0-milestone-6
1.0-milestone-7
1.0-milestone-8
1.0-milestone-8a
1.0-milestone-9
1.0-rc-1
1.0-rc-2
1.0-rc-3
1.1
1.10
1.10-rc-1
1.10-rc-2
1.11
1.11-rc-1
1.12
1.12-rc-1
1.12-rc-2
1.1-rc-1
1.1-rc-2
1.2
1.2-rc-1
1.3
1.3-rc-1
1.3-rc-2
1.4
1.4-rc-1
1.4-rc-2
1.4-rc-3
1.5
1.5-rc-1
1.5-rc-2
1.5-rc-3
1.6
1.6-rc-1
1.7
1.7-rc-1
1.7-rc-2
1.8
1.8-rc-1
1.8-rc-2
1.9
1.9-rc-1
1.9-rc-2
1.9-rc-3
1.9-rc-4
2.0
2.0-rc-1
2.0-rc-2
2.1
2.10
2.10-rc-1
2.10-rc-2
2.11
2.11-rc-1
2.11-rc-2
2.11-rc-3
2.12
2.12-rc-1
2.13
2.13-rc-1
2.13-rc-2
2.14
2.14.1
2.14.1-rc-1
2.14.1-rc-2
2.14-rc-1
2.14-rc-2
2.14-rc-3
2.14-rc-4
2.14-rc-5
2.14-rc-6
2.1-rc-1
2.1-rc-2
2.1-rc-3
2.1-rc-4
2.2
2.2.1
2.2.1-rc-1
2.2-rc-1
2.2-rc-2
2.3
2.3-rc-1
2.3-rc-2
2.3-rc-3
2.3-rc-4
2.4
2.4-rc-1
2.4-rc-2
2.5
2.5-rc-1
2.5-rc-2
2.6
2.6-rc-1
2.6-rc-2
2.7
2.7-rc-1
2.7-rc-2
2.8
2.8-rc-1
2.8-rc-2
2.9
2.9-rc-1
3.0
3.0-milestone-1
3.0-milestone-2
3.0-rc-1
3.0-rc-2
3.1
3.1-rc-1
3.2
3.2.1
3.2-rc-1
3.2-rc-2
3.2-rc-3
3.3
3.3-rc-1
3.4
3.4.1
3.4-rc-1
3.4-rc-2
3.4-rc-3
3.5
3.5.1
3.5-rc-1
3.5-rc-2
3.5-rc-3
4.0
4.0.1
4.0.2
4.0-milestone-1
4.0-milestone-2
4.0-rc-1
4.0-rc-2
4.0-rc-3
4.1
4.10
4.10.1
4.10.2
4.10.3
4.10-rc-1
4.10-rc-2
4.10-rc-3
4.1-milestone-1
4.1-rc-1
4.1-rc-2
4.2
4.2.1
4.2-rc-1
4.2-rc-2
4.3
4.3.1
4.3-rc-1
4.3-rc-2
4.3-rc-3
4.3-rc-4
4.4
4.4.1
4.4-rc-1
4.4-rc-2
4.4-rc-3
4.4-rc-4
4.4-rc-5
4.4-rc-6
4.5
4.5.1
4.5-rc-1
4.5-rc-2
4.6
4.6-rc-1
4.6-rc-2
4.7
4.7-rc-1
4.7-rc-2
4.8
4.8.1
4.8-rc-1
4.8-rc-2
4.8-rc-3
4.9
4.9-rc-1
4.9-rc-2
5.0
5.0-milestone-1
5.0-rc-1
5.0-rc-2
5.0-rc-3
5.0-rc-4
5.0-rc-5
5.1
5.1.1
5.1-milestone-1
5.1-rc-1
5.1-rc-2
5.1-rc-3
5.2
5.2.1
5.2-rc-1
5.3
5.3.1
5.3-rc-1
5.3-rc-2
5.3-rc-3
5.4
5.4.1
5.4-rc-1
5.5
5.5.1
5.5-rc-1
5.5-rc-2
5.5-rc-3
5.5-rc-4
5.6
5.6.1
5.6.2
5.6.3
5.6.4
5.6-rc-1
5.6-rc-2
6.0
6.0.1
6.0-rc-1
6.0-rc-2
6.0-rc-3
6.1
6.1.1
6.1-milestone-1
6.1-milestone-2
6.1-milestone-3
6.1-rc-1
6.1-rc-2
6.1-rc-3
6.2
6.2.1
6.2.2
6.2-rc-1
6.2-rc-2
6.2-rc-3
6.3
6.3-rc-1
6.3-rc-2
6.3-rc-3
6.3-rc-4
6.4
6.4.1
6.4-rc-1
6.4-rc-2
6.4-rc-3
6.4-rc-4
6.5
6.5.1
6.5-milestone-1
6.5-milestone-2
6.5-rc-1
6.6
6.6.1
6.6-milestone-1
6.6-milestone-2
6.6-milestone-3
6.6-rc-1
6.6-rc-2
6.6-rc-3
6.6-rc-4
6.6-rc-5
6.6-rc-6
6.7
6.7.1
6.7-rc-1
6.7-rc-2
6.7-rc-3
6.7-rc-4
6.7-rc-5
6.8
6.8.1
6.8.2
6.8.3
6.8-milestone-1
6.8-milestone-2
6.8-milestone-3
6.8-rc-1
6.8-rc-2
6.8-rc-3
6.8-rc-4
6.8-rc-5
6.9
6.9.1
6.9.2
6.9-rc-1
6.9-rc-2
7.0
7.0.1
7.0.2
7.0-milestone-1
7.0-milestone-2
7.0-milestone-3
7.0-rc-1
7.0-rc-2
7.1
7.1.1
7.1-rc-1
7.1-rc-2
7.2
7.2-rc-1
7.2-rc-2
7.2-rc-3
7.3
7.3.1
7.3.2
7.3.3
7.3.3-rc-1
7.3-rc-1
7.3-rc-2
7.3-rc-3
7.3-rc-4
7.3-rc-5
7.4
7.4.1
7.4.2
7.4-rc-1
7.4-rc-2
7.5
7.5.1
7.5-milestone-1
7.5-rc-1
7.5-rc-2
7.5-rc-3
7.5-rc-4
7.5-rc-5
```

And with the entire commando withou -n argument:

```
curl -s https://services.gradle.org/distributions/ | grep -e "distributions.*-bin.zip\"" | sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##" | sort -t. | paste -s -d" " - 
0.7 0.8 0.9 0.9.1 0.9.2 0.9-rc-1 0.9-rc-2 0.9-rc-3 1.0 1.0-milestone-1 1.0-milestone-2 1.0-milestone-2a 1.0-milestone-3 1.0-milestone-4 1.0-milestone-5 1.0-milestone-6 1.0-milestone-7 1.0-milestone-8 1.0-milestone-8a 1.0-milestone-9 1.0-rc-1 1.0-rc-2 1.0-rc-3 1.1 1.10 1.10-rc-1 1.10-rc-2 1.11 1.11-rc-1 1.12 1.12-rc-1 1.12-rc-2 1.1-rc-1 1.1-rc-2 1.2 1.2-rc-1 1.3 1.3-rc-1 1.3-rc-2 1.4 1.4-rc-1 1.4-rc-2 1.4-rc-3 1.5 1.5-rc-1 1.5-rc-2 1.5-rc-3 1.6 1.6-rc-1 1.7 1.7-rc-1 1.7-rc-2 1.8 1.8-rc-1 1.8-rc-2 1.9 1.9-rc-1 1.9-rc-2 1.9-rc-3 1.9-rc-4 2.0 2.0-rc-1 2.0-rc-2 2.1 2.10 2.10-rc-1 2.10-rc-2 2.11 2.11-rc-1 2.11-rc-2 2.11-rc-3 2.12 2.12-rc-1 2.13 2.13-rc-1 2.13-rc-2 2.14 2.14.1 2.14.1-rc-1 2.14.1-rc-2 2.14-rc-1 2.14-rc-2 2.14-rc-3 2.14-rc-4 2.14-rc-5 2.14-rc-6 2.1-rc-1 2.1-rc-2 2.1-rc-3 2.1-rc-4 2.2 2.2.1 2.2.1-rc-1 2.2-rc-1 2.2-rc-2 2.3 2.3-rc-1 2.3-rc-2 2.3-rc-3 2.3-rc-4 2.4 2.4-rc-1 2.4-rc-2 2.5 2.5-rc-1 2.5-rc-2 2.6 2.6-rc-1 2.6-rc-2 2.7 2.7-rc-1 2.7-rc-2 2.8 2.8-rc-1 2.8-rc-2 2.9 2.9-rc-1 3.0 3.0-milestone-1 3.0-milestone-2 3.0-rc-1 3.0-rc-2 3.1 3.1-rc-1 3.2 3.2.1 3.2-rc-1 3.2-rc-2 3.2-rc-3 3.3 3.3-rc-1 3.4 3.4.1 3.4-rc-1 3.4-rc-2 3.4-rc-3 3.5 3.5.1 3.5-rc-1 3.5-rc-2 3.5-rc-3 4.0 4.0.1 4.0.2 4.0-milestone-1 4.0-milestone-2 4.0-rc-1 4.0-rc-2 4.0-rc-3 4.1 4.10 4.10.1 4.10.2 4.10.3 4.10-rc-1 4.10-rc-2 4.10-rc-3 4.1-milestone-1 4.1-rc-1 4.1-rc-2 4.2 4.2.1 4.2-rc-1 4.2-rc-2 4.3 4.3.1 4.3-rc-1 4.3-rc-2 4.3-rc-3 4.3-rc-4 4.4 4.4.1 4.4-rc-1 4.4-rc-2 4.4-rc-3 4.4-rc-4 4.4-rc-5 4.4-rc-6 4.5 4.5.1 4.5-rc-1 4.5-rc-2 4.6 4.6-rc-1 4.6-rc-2 4.7 4.7-rc-1 4.7-rc-2 4.8 4.8.1 4.8-rc-1 4.8-rc-2 4.8-rc-3 4.9 4.9-rc-1 4.9-rc-2 5.0 5.0-milestone-1 5.0-rc-1 5.0-rc-2 5.0-rc-3 5.0-rc-4 5.0-rc-5 5.1 5.1.1 5.1-milestone-1 5.1-rc-1 5.1-rc-2 5.1-rc-3 5.2 5.2.1 5.2-rc-1 5.3 5.3.1 5.3-rc-1 5.3-rc-2 5.3-rc-3 5.4 5.4.1 5.4-rc-1 5.5 5.5.1 5.5-rc-1 5.5-rc-2 5.5-rc-3 5.5-rc-4 5.6 5.6.1 5.6.2 5.6.3 5.6.4 5.6-rc-1 5.6-rc-2 6.0 6.0.1 6.0-rc-1 6.0-rc-2 6.0-rc-3 6.1 6.1.1 6.1-milestone-1 6.1-milestone-2 6.1-milestone-3 6.1-rc-1 6.1-rc-2 6.1-rc-3 6.2 6.2.1 6.2.2 6.2-rc-1 6.2-rc-2 6.2-rc-3 6.3 6.3-rc-1 6.3-rc-2 6.3-rc-3 6.3-rc-4 6.4 6.4.1 6.4-rc-1 6.4-rc-2 6.4-rc-3 6.4-rc-4 6.5 6.5.1 6.5-milestone-1 6.5-milestone-2 6.5-rc-1 6.6 6.6.1 6.6-milestone-1 6.6-milestone-2 6.6-milestone-3 6.6-rc-1 6.6-rc-2 6.6-rc-3 6.6-rc-4 6.6-rc-5 6.6-rc-6 6.7 6.7.1 6.7-rc-1 6.7-rc-2 6.7-rc-3 6.7-rc-4 6.7-rc-5 6.8 6.8.1 6.8.2 6.8.3 6.8-milestone-1 6.8-milestone-2 6.8-milestone-3 6.8-rc-1 6.8-rc-2 6.8-rc-3 6.8-rc-4 6.8-rc-5 6.9 6.9.1 6.9.2 6.9-rc-1 6.9-rc-2 7.0 7.0.1 7.0.2 7.0-milestone-1 7.0-milestone-2 7.0-milestone-3 7.0-rc-1 7.0-rc-2 7.1 7.1.1 7.1-rc-1 7.1-rc-2 7.2 7.2-rc-1 7.2-rc-2 7.2-rc-3 7.3 7.3.1 7.3.2 7.3.3 7.3.3-rc-1 7.3-rc-1 7.3-rc-2 7.3-rc-3 7.3-rc-4 7.3-rc-5 7.4 7.4.1 7.4.2 7.4-rc-1 7.4-rc-2 7.5 7.5.1 7.5-milestone-1 7.5-rc-1 7.5-rc-2 7.5-rc-3 7.5-rc-4 7.5-rc-5

```

And without -n on list-all script:

![image](https://user-images.githubusercontent.com/22268900/191387874-35a98af8-d8ae-4c02-9a73-837bd5cfbc5e.png)

**Comment by luisangelorjr** [comment] 2022-09-21 00:37
> Can you (a) make sure you're using the current version of the plugin

Yes, the current on master branch.

And after the first comment on this issue I'm clone the project on my personal notebook (the same of the screenshots) and same error

---
Curious fact (but I dont think is the root of problem): The three notebooks with the error use pt-br language base

**Comment by rfrancis** [comment] 2022-09-21 13:49
I was just about to ask what you have LANG set to when I saw your note at the bottom. I do in fact think the problem is internationalization-based; I can't think of any other reason that sort -n would act differently.  From "man sort" on my Linux box:

> *** WARNING *** The locale specified by the environment affects sort order.  Set LC_ALL=C to get the traditional sort order that  uses native byte values.

So you might play around with that to see if it corrects the issue, and if so we can update the scripts to set LC_ALL or whatever else works.

**Comment by luisangelorjr** [comment] 2022-09-21 13:54
OMG:

![image](https://user-images.githubusercontent.com/22268900/191522956-6f3142a3-19ae-48c7-a726-ff9d4ee0f2d2.png)

**Comment by rfrancis** [comment] 2022-09-21 14:01
Should be fixed in https://github.com/rfrancis/asdf-gradle/commit/e47df002ad0b3efa76bb997ace9d12bf6de1a063 -- feel free to reopen if not.

**Closed as completed by rfrancis** 2022-09-21 14:01 UTC
